[package]
name = "egomoose/better-view-selector"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "stravant/goodsignal@0.2.1"
Janitor = "howmanysmall/janitor@1.15.7"
LuaEncode = "regginator/luaencode@1.3.1"