[package]
name = "egomoose/better-view-selector"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
private = true

[dependencies]
React = "jsdotlua/react@17.2.1"
ReactRoblox = "jsdotlua/react-roblox@17.2.1"