[package]
name = "egomoose/better-view-selector"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@1.4.0"
Signal = "sleitnick/signal@2.0.1"
LuaEncode = "regginator/luaencode@1.3.1"